version: '3'

networks:
  carnetwork:
    external: false

services:
  car-service:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - '8080:8080'
    environment:
      spring.profiles.active: dev
    depends_on:
      - mysql
      - kafka
    networks:
      - default
      - carnetwork

  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default
      - carnetwork

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
    hostname: zookeeper
    networks:
      - default
      - carnetwork

  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - default
      - carnetwork


